mysite/enquetes/urls.py
from django.urls import path

from . import views

app_name = 'enquetes'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('create/', views.createView, name = 'create')
]

mysite/inrite/urls.py
from django.urls import path

from . import views

app_name = 'inrite'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('enquetes/', include('enquetes.urls')),
    path('admin/', admin.site.urls),
    path('inrite/', include('inrite.urls')),
]

mysite/enquetes/models.py
import datetime
from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published',default=timezone.now())
    all_votes = models.IntegerField(default=0)
    category = models.CharField(max_length=100, default="")
    
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    def __str__(self):
        return self.question_text



class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mysite/inrite/models.py
import datetime
from django.db import models
from django.utils import timezone
from PIL import Image


class Usuario(models.Model):
    nome = models.CharField(max_length=200)
    email = models.EmailField(max_length=100)
    senha = models.CharField(max_length=100)
    avatar = models.ImageField(upload_to='media/avatar')

    um = '1'
    dois = '2'
    tres = '3'
    tipo_de_usuario = [
        (um, 'Administrador'),
        (dois, 'Colunista'),
        (tres, 'Leitor'),
    ]
    tipo = models.CharField(max_length=1, choices=tipo_de_usuario, default=3)

class Edicao(models.Model):
    usuario_id = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=200)
    data = models.DateTimeField('data de publicação', default=timezone.now())

    def publicado_recentemente(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.data <= now

    def __str__(self):
        return self.titulo


class Noticia(models.Model):
    usuario_id = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    edicao_id = models.ForeignKey(Edicao, on_delete=models.CASCADE)

    titulo = models.CharField(max_length=200)
    descricao = models.CharField(max_length=500)
    thumbnail = models.ImageField(upload_to='media/thumbnail')
    conteudo = models.TextField(default='')
    data = models.DateTimeField('data de publicação', default=timezone.now())
    categoria = models.CharField(max_length=100)

    def publicado_recentemente(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.data <= now

    def __str__(self):
        return self.titulo


class Comentario(models.Model):
    usuario_id = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    edicao_id = models.ForeignKey(Edicao, on_delete=models.CASCADE)
    noticia_id = models.ForeignKey(Noticia, on_delete=models.CASCADE)
    conteudo = models.CharField(max_length=500)
    data = models.DateTimeField('data de publicação', default=timezone.now())
    curtidas = models.IntegerField(default=0)

    def publicado_recentemente(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.data <= now

    def __str__(self):
        return self.conteudo

mysite/enquetes/views.py
from unicodedata import category
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy,reverse
from django.views import generic
from django.utils import timezone
from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'enquetes/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'enquetes/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'enquetes/results.html'

def createView(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        category = request.POST.get('category')
        option1 = request.POST.get('option1')
        option2 = request.POST.get('option2')
        option3 = request.POST.get('option3')

        questionCreation = Question.objects.create(question_text = title, category = category)
        choiceOneCreation = Choice.objects.create(question = questionCreation, choice_text = option1)
        choiceTwoCreation = Choice.objects.create(question = questionCreation, choice_text = option2)
        choiceThreeCreation = Choice.objects.create(question = questionCreation, choice_text = option3)
        return HttpResponseRedirect(reverse('enquetes:index'))

    return render(request, "enquetes/create.html")


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'enquetes/detail.html', {
            'question': question,
            'error_message': "Escolha uma alternativa.",
        })
    else:
        questionId = Question.objects.get(pk=question_id)
        questionId.all_votes += 1
        questionId.save()
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('enquetes:results', args=(question.id,)))

mysite/inrite/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import View
from django.utils import timezone
from .models import Usuario, Edicao, Noticia


class IndexView(View):
    def get(self, request, *args, **kwargs):
        ultimas_noticias = Noticia.objects.filter(data__lte=timezone.now()).order_by('-data')[:5]
        return render(request, "index.html", {'ultimas_noticias': ultimas_noticias})

mysite/enquetes/templates/enquetes/create.html
<!DOCTYPE html>
<html>

<head>
    <meta charset='utf-8'>
    <title>Enquetes</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'enquetes/style-create.css' %}">
    <link rel="stylesheet" href="{% static 'enquetes/nav.css' %}">
    <link rel="stylesheet" href="{% static 'enquetes/colors.css' %}">

</head>

<body>
    <nav class="nav">
        <div class="nav-left"></div>

        <div class="nav-center">
            <a href="{% url 'enquetes:index' %}" class="nav--link colorGrey">Todas Enquetes</a>
            <a href="{% url 'enquetes:create' %}" class="nav--link colorGreen">Criar Enquetes</a>
        </div>

        <div class="nav-rigth">
            <div class="hamburger-menu">
                <div class="ham-bar bar-top"></div>
                <div class="ham-bar bar-mid"></div>
                <div class="ham-bar bar-bottom"></div>
            </div>
        </div>
    </nav>

    <div class="nav-mobile">
        <div class="div-mobile">
            <nav class="nav-links">
                <a href="{% url 'enquetes:index' %}" class="links-mobile colorGrey">Todas Enquetes</a>
            </nav>

        </div>
    </div>

    <main class="main">
        <section class="main-section">
            <header>
                <h1 class="title">Crie uma enquete</h1>
                <p class="subtitle">Complete todos os dados para criar uma nova enquete.</p>
            </header>

            <div class="list">
                <form action="{% url 'enquetes:create' %}" method="post">
                    {% csrf_token %}
                    <div class="div">
                        <label for="title">Titulo da enquete</label>
                        <textarea placeholder="Ex: Qual é seu time?" type="text" name="title"
                            id="title-form"></textarea>
                    </div>

                    <div class="div">
                        <label for="option1">Categoria</label>
                        <select name="category" id="category" name="category" class="input-selection">
                            <option value disabled selected>Escolha a categoria</option>
                            <option value="Animais">Animais</option>
                            <option value="Arte">Arte</option>
                            <option value="Aleatório">Aleatório</option>
                            <option value="Comida">Comidas</option>
                            <option value="Filmes">Filmes</option>
                            <option value="Livros">Livros</option>
                            <option value="Musicas">Músicas</option>

                        </select>
                    </div>


                    <div class="division"></div>

                    <div class="div">
                        <label for="option1">Opção de enquete</label>
                        <input class="option" placeholder="Opção 1" type="text" name="option1" id="option1-form">
                    </div>

                    <div class="div">
                        <label for="option2">Opção de enquete</label>
                        <input class="option" placeholder="Opção 2" type="text" name="option2" id="option2-form">
                    </div>

                    <div class="div">
                        <label for="option3">Opção de enquete</label>
                        <input class="option" placeholder="Opção 3" type="text" name="option3" id="option3-form">
                    </div>
                    <input class="button" type="submit" value="Cadastrar Enquete">
                </form>
            </div>
        </section>
    </main>

    <script src="{% static 'enquetes/js/nav.js' %}"></script>
</body>

</html>

mysite/enquetes/templates/enquetes/detail.html
<!DOCTYPE html>
<html>

<head>
    <meta charset='utf-8'>
    <title>Enquetes</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'enquetes/style_detail.css' %}">
    <script src="{% static 'enquetes/js/detail.js' %}"></script>
    <link rel="stylesheet" href="{% static 'enquetes/nav.css' %}">
    <link rel="stylesheet" href="{% static 'enquetes/colors.css' %}">
</head>

<body>
    <nav class="nav">
        <div class="nav-left"></div>

        <div class="nav-center">
            <a href="{% url 'enquetes:index' %}" class="nav--link colorGrey">Todas Enquetes</a>
            <a href="{% url 'enquetes:create' %}" class="nav--link colorGreen">Criar Enquetes</a>
        </div>

        <div class="nav-rigth">
            <div class="hamburger-menu">
                <div class="ham-bar bar-top"></div>
                <div class="ham-bar bar-mid"></div>
                <div class="ham-bar bar-bottom"></div>
            </div>
        </div>
    </nav>

    <div class="nav-mobile">
        <div class="div-mobile">
            <nav class="nav-links">
                <a href="{% url 'enquetes:index' %}" class="links-mobile colorGrey">Todas Enquetes</a>
            </nav>

        </div>
    </div>


    <main class="main">
        <section class="main-section">
            <form action="{% url 'enquetes:vote' question.id %}" method="post">
                {% csrf_token %}
                <header>
                    <h1 class="title">{{ question.question_text }}</h1>
                    <p class="subtitle">{{ question.pub_date }}</p>
                </header>

                <div class="div">
                    <main>
                        {% if error_message %}<p class="erro"><strong>{{ error_message }}</strong></p>{% endif %}

                        {% for choice in question.choice_set.all %}
                        <div class="choice" onclick="choice({{ forloop.counter }})">
                            <input class="choicebutton" type="radio" name="choice" id="choice{{ forloop.counter }}"
                                value="{{ choice.id }}">
                            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
                        </div>

                        {% endfor %}
                    </main>

                    <aside>
                        <input class="submitbutton" type="submit" value="Confirmar">
                        <div class="votes">
                            <div class="div_votes">
                                <p>votos</p>
                                <h1>{{ question.all_votes }}</h1>
                            </div>
                            <a href="{% url 'enquetes:index' %}">
                                <div class="div_back">
                                    <p>Voltar</p>
                                </div>
                            </a>
                        </div>
                    </aside>
                </div>

            </form>
        </section>
    </main>
    <script src="{% static 'enquetes/js/nav.js' %}"></script>
</body>

</html>

mysite/enquetes/templates/enquetes/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset='utf-8'>
    <title>Enquetes</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'enquetes/style.css' %}">
    <link rel="stylesheet" href="{% static 'enquetes/nav.css' %}">
    <link rel="stylesheet" href="{% static 'enquetes/colors.css' %}">

</head>

<body>
    <nav class="nav">
        <div class="nav-left"></div>

        <div class="nav-center">
            <a href="{% url 'enquetes:index' %}" class="nav--link colorGrey">Todas Enquetes</a>
            <a href="{% url 'enquetes:create' %}" class="nav--link colorGreen">Criar Enquetes</a>
        </div>

        <div class="nav-rigth">
            <div class="hamburger-menu">
                <div class="ham-bar bar-top"></div>
                <div class="ham-bar bar-mid"></div>
                <div class="ham-bar bar-bottom"></div>
            </div>
        </div>
    </nav>

    <div class="nav-mobile">
        <div class="div-mobile">
            <nav class="nav-links">
                <a href="{% url 'enquetes:index' %}" class="links-mobile colorGrey">Todas Enquetes</a>
            </nav>

        </div>
    </div>

    <main class="main">
        <section class="main-section">
            <header>
                <h1 class="title">Enquetes</h1>
                <p class="subtitle">Essas são as enquetes criadas mais recentes.</p>
            </header>

            <div class="list">

                {% if latest_question_list %}

                {% for question in latest_question_list %}
                <div class="div-item">
                    <a class="link-item" href="{% url 'enquetes:detail' question.id %}">

                        <p class="category {{ question.category }} ">{{ question.category }}</p>
                        <h2 class="title">{{ question.question_text }}</h2>
                        <p class="date">{{ question.pub_date }}</p>
                        <div class="votes">
                            <p>{{ question.all_votes }} votos</p>
                        </div>
                    </a>
                </div>
                {% endfor %}


                {% else %}

                <p>Não existe nenhuma enquete.</p>

                {% endif %}


            </div>
        </section>
    </main>

    <script src="{% static 'enquetes/js/nav.js' %}"></script>
</body>

</html>

mysite/enquetes/templates/enquetes/results.html
<!DOCTYPE html>
<html>

<head>
    <meta charset='utf-8'>
    <title>Enquetes</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'enquetes/style_results.css' %}">
    <link rel="stylesheet" href="{% static 'enquetes/nav.css' %}">
    <link rel="stylesheet" href="{% static 'enquetes/colors.css' %}">
    <script src="{% static 'enquetes/js/detail.js' %}"></script>
</head>

<body>
    <nav class="nav">
        <div class="nav-left"></div>

        <div class="nav-center">
            <a href="{% url 'enquetes:index' %}" class="nav--link colorGrey">Todas Enquetes</a>
            <a href="{% url 'enquetes:create' %}" class="nav--link colorGreen">Criar Enquetes</a>
        </div>

        <div class="nav-rigth">
            <div class="hamburger-menu">
                <div class="ham-bar bar-top"></div>
                <div class="ham-bar bar-mid"></div>
                <div class="ham-bar bar-bottom"></div>
            </div>
        </div>
    </nav>

    <div class="nav-mobile">
        <div class="div-mobile">
            <nav class="nav-links">
                <a href="{% url 'enquetes:index' %}" class="links-mobile colorGrey">Todas Enquetes</a>
            </nav>

        </div>
    </div>

    <main class="main">
        <section class="main-section">
            <form action="{% url 'enquetes:vote' question.id %}" method="post">
                {% csrf_token %}
                <header>
                    <h1 class="title">{{ question.question_text }}</h1>
                    <p class="subtitle">{{ question.pub_date }}</p>
                </header>

                <div class="div">
                    <main>
                        {% if error_message %}<p class="erro"><strong>{{ error_message }}</strong></p>{% endif %}

                        {% for choice in question.choice_set.all %}
                        <div class="choice" onclick="choice({{ forloop.counter }})">
                            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>

                            <p>{{ choice.votes }} voto{{ choice.votes|pluralize }}</p>
                        </div>

                        {% endfor %}
                    </main>

                    <aside>
                        <a href="{% url 'enquetes:detail' question.id %}" class="submitbutton">Votar novamente</a>
                        <div class="votes">
                            <div class="div_votes">
                                <p>Total de votos</p>
                                <h1>{{ question.all_votes }}</h1>
                            </div>
                            <a href="{% url 'enquetes:index' %}">
                                <div class="div_back">
                                    <p>Voltar ao Início</p>
                                </div>
                            </a>
                        </div>
                    </aside>
                </div>
            </form>
        </section>

    </main>
    <script src="{% static 'enquetes/js/nav.js' %}"></script>
</body>

</html>

mysite/inrite/templates/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Page Title</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <!-- <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script> -->
</head>

<body>
    {% load static %}
    <h1>Últimas Noticias</h1>

    {% if ultimas_noticias %}

    {% for noticia in ultimas_noticias %}
    <div class="div">
        <img src="{{noticia.thumbnail}}" style="
                        width: 13em;
                        height: 5em;
                    ">
        <p>{{ noticia.categoria }}</p>
        <h2>{{ noticia.titulo }}</h2>
    </div>
    {% endfor %}


    {% else %}

    <p>Não existe nenhuma Noticia.</p>

    {% endif %}

</body>

</html>